### ISSUE TITLE
Variation Bundle prices do not respect price/tax display settings

### ISSUE THREAD

**Issue by jimjasson** [somewherewarm/woocommerce-product-bundles-variation-bundles#14]
### Description

When adding a Product Bundle as a Variation Bundle, then the variation prices are replaced by the Bundle prices. However, the Bundle prices we pass to the variation are always "excluding" tax/raw prices. If the shop price display settings are set to "including" tax, then this leads to an inaccurate Catalog Price for the Variable Product that includes the Bundle as well as an inaccurate variation price. 

### Source

Zendesk #4606000

### Steps to replicate
1. Set the store's tax settings to: a) **Prices entered with tax > No, I will enter prices exclusive of tax** and b) **Display prices in the shop > Including tax**.
2. Create a static Product Bundle.
3. Create a Variable Product with 2 variations. 
4. Add a Bundle as a Variation Bundle for one of the two variations. 
5. View the Variable Product -- both the Catalog Price + the variation price (after you select a variation) will be displayed without tax.

**Comment by jimjasson** [comment]
As I mentioned in the issue description, it seems that we always pass raw prices, excluding tax to Variation Bundles. 

We change the variation prices in 4 locations: 
- `woocommerce_product_variation_get_price`
- `woocommerce_product_variation_get_regular_price`
- `woocommerce_product_variation_get_sale_price`
- `woocommerce_variation_prices`.

The fourth hook (`woocommerce_variation_prices`) can optionally take a 3rd argument called `$for_display` that determines if the prices will be displayed or if they will be used for internal calculations. We could use this argument to pass prices including/excluding tax -- for example: https://d.pr/i/gei08Y. This fixes the Catalog Price error.

The rest 3 hooks do not have a similar argument. The only solution I found there was to always check the tax display setting like so: https://d.pr/i/y7o9gA. This fixes the variation price error. 

This approach requires adding significant amount of code to Variation Bundles. I would love some feedback on whether it is the right one before making a PR for this.

**Comment by manospsyx** [comment]
> As I mentioned in the issue description, it seems that we always pass raw prices, excluding tax to Variation Bundles.

Price getters are always "raw". The only exception appears to be `get_variation_prices`, which accepts the `$for_display` argument.

I am onboard with your approach to introduce that 3rd argument to the callback 👍

Note for the future: There could be more issues/bugs that we will not be able to address, in cases that involve bundles that contain items with different tax rates (or different from the container tax rate).

The reason behind this is that, if (for example) prices are defined excl tax, but displayed incl tax, and some code in the wild attempts to calculate variation prices for display, Variation Bundles will make the variation inherit the tax rate of the bundle container, and apply a single tax rate over the inherited raw price (excl tax). Price calculations in bundles that contain items with multiple tax rates are a bit more complex than this. Does this make sense?

**Comment by jimjasson** [comment]
Thank you @manospsyx !

> Price getters are always "raw". The only exception appears to be get_variation_prices, which accepts the $for_display argument.

Modifying the `get_variation_prices` resolves the issue with the Catalog Price. However, the price of the selected variation is still always excluding tax when this variation includes a Bundle. 

Is there any other way to approach the incorrect variation price issue apart from modifying the callbacks I mentioned above? I will do some investigation on this but any tips are welcome! 

> Note for the future: There could be more issues/bugs that we will not be able to address, in cases that involve bundles that contain items with different tax rates (or different from the container tax rate).

> The reason behind this is that, if (for example) prices are defined excl tax, but displayed incl tax, and some code in the wild attempts to calculate variation prices for display, Variation Bundles will make the variation inherit the tax rate of the bundle container, and apply a single tax rate over the inherited raw price (excl tax). Price calculations in bundles that contain items with multiple tax rates are a bit more complex than this. Does this make sense?

It does! Thank you for raising this!

**Comment by manospsyx** [comment]
> Is there any other way to approach the incorrect variation price issue apart from modifying the callbacks I mentioned above? I will do some investigation on this but any tips are welcome!

@jimjasson I'm not sure why that happens!

Variation prices are rendered via `get_price_html` [here](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/class-wc-product-variable.php#L382) (see https://github.com/woocommerce/woocommerce/blob/55aef5f2225522499bdae0e21ee259cffb4c8bb2/plugins/woocommerce/includes/abstracts/abstract-wc-product.php#L1826)

Did you look in there to figure out the cause? Since we are inheriting the tax class, I would not expect to see any issues there, **unless** the bundle contains items with different tax rates than the container product itself.

**Comment by jimjasson** [comment]
Had another look at this and it turns out that `woocommerce_variation_prices` is enough to override both the Catalog Price and the variation price. The reason why this wasn't working for me before was that I had set the Variable Product to non-taxable. If the Variable Product is not taxable, then the variations automatically become not taxable as well. 

In Variation Bundles, we always override the tax status of the variation, without first checking if the Variable Product is taxable or not. Variation Bundles should only replace the tax setting of the variation and not override any changes that are made based on the tax status of the parent Variable Product.
